// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_api_keys.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO device_api_keys (device_id, key_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, device_id, key_hash, created_at, expires_at, last_used_at, deleted_at
`

type CreateAPIKeyParams struct {
	DeviceID  pgtype.UUID
	KeyHash   string
	ExpiresAt pgtype.Timestamptz
}

// Inserts a new API key. The caller must bcrypt-hash the key before storing;
// the plain key is returned to the admin only at creation time and never again.
// expires_at is nullable: NULL = no expiration.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (DeviceApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.DeviceID, arg.KeyHash, arg.ExpiresAt)
	var i DeviceApiKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveKeyByDeviceID = `-- name: GetActiveKeyByDeviceID :one
SELECT id, device_id, key_hash, created_at, expires_at, last_used_at, deleted_at
FROM device_api_keys
WHERE device_id = $1 AND deleted_at IS NULL
`

// Pre-check used by the application service before issuing a new key.
// The new partial UNIQUE index on (device_id) WHERE deleted_at IS NULL
// is the source of truth; this query exists only to surface a friendly
// 409 error path on the common case (without it the user gets a raw
// SQLSTATE 23505). Soft-deleted rows are ignored — revoked keys do not
// count against the single-active-key invariant.
func (q *Queries) GetActiveKeyByDeviceID(ctx context.Context, deviceID pgtype.UUID) (DeviceApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveKeyByDeviceID, deviceID)
	var i DeviceApiKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveKeyByHash = `-- name: GetActiveKeyByHash :one
SELECT id, device_id, key_hash, created_at, expires_at, last_used_at, deleted_at
FROM device_api_keys
WHERE key_hash = $1
  AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

// Hot auth path for the IoT device authentication.
// The device sends X-Device-Key: <plain>; the backend bcrypt-hashes it and
// looks up by hash. Filters out soft-deleted and expired keys.
// The Go layer is responsible for verifying that the key's device_id
// matches the device_id from the URL/path.
func (q *Queries) GetActiveKeyByHash(ctx context.Context, keyHash string) (DeviceApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveKeyByHash, keyHash)
	var i DeviceApiKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.KeyHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAPIKeysForDevice = `-- name: ListAPIKeysForDevice :many
SELECT id, device_id, key_hash, created_at, expires_at, last_used_at, deleted_at
FROM device_api_keys
WHERE device_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Returns all active keys for a device, for the admin UI.
// Does NOT return the plain key (it was never stored).
func (q *Queries) ListAPIKeysForDevice(ctx context.Context, deviceID pgtype.UUID) ([]DeviceApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceApiKey
	for rows.Next() {
		var i DeviceApiKey
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.KeyHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPIKeyUsed = `-- name: MarkAPIKeyUsed :exec
UPDATE device_api_keys
SET last_used_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Updates last_used_at on every successful auth. Cheap, no RETURNING.
// Lets the admin UI show "last seen" per key.
func (q *Queries) MarkAPIKeyUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAPIKeyUsed, id)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE device_api_keys
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft-deletes the key. Used for rotation: create a new key, then revoke
// the old one. Soft delete + UNIQUE partial index on the hash means
// a new key with the same hash can be created immediately (the old row
// no longer occupies the unique constraint).
func (q *Queries) RevokeAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}
