// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (uuid_firmware, name)
VALUES ($1, $2)
RETURNING id, uuid_firmware, name, created_at, last_seen_at, deleted_at
`

type CreateDeviceParams struct {
	UuidFirmware string
	Name         string
}

// Creates a new device. uuid_firmware must be globally unique (DB-enforced).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UuidFirmware, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, uuid_firmware, name, created_at, last_seen_at, deleted_at
FROM devices
WHERE id = $1 AND deleted_at IS NULL
`

// Standard lookup by primary key. Filters out soft-deleted devices.
func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByIDForUser = `-- name: GetDeviceByIDForUser :one
SELECT
  d.id,
  d.uuid_firmware,
  d.name,
  d.created_at,
  d.last_seen_at,
  uda.role AS access_role
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE d.id = $1
  AND uda.user_id = $2
  AND d.deleted_at IS NULL
`

type GetDeviceByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetDeviceByIDForUserRow struct {
	ID           pgtype.UUID
	UuidFirmware string
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	AccessRole   string
}

// Returns the device only if the given user has access (any role).
// Returns sql.ErrNoRows when the device does not exist OR the user has no
// access. The handler maps both to 404 to avoid leaking which IDs exist.
func (q *Queries) GetDeviceByIDForUser(ctx context.Context, arg GetDeviceByIDForUserParams) (GetDeviceByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByIDForUser, arg.ID, arg.UserID)
	var i GetDeviceByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AccessRole,
	)
	return i, err
}

const getDeviceByUUIDFirmware = `-- name: GetDeviceByUUIDFirmware :one
SELECT id, uuid_firmware, name, created_at, last_seen_at, deleted_at
FROM devices
WHERE uuid_firmware = $1 AND deleted_at IS NULL
`

// Hot auth path for the IoT device authentication flow.
// The ESP32 sends its uuid_firmware, the backend resolves it to a device row.
func (q *Queries) GetDeviceByUUIDFirmware(ctx context.Context, uuidFirmware string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByUUIDFirmware, uuidFirmware)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT
  d.id,
  d.uuid_firmware,
  d.name,
  d.created_at,
  d.last_seen_at,
  uda.role AS access_role
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
`

type ListDevicesForUserRow struct {
	ID           pgtype.UUID
	UuidFirmware string
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	AccessRole   string
}

// Returns the devices the given user has access to, with the access role
// from user_device_access. Used by the dashboard "my devices" view.
// Filters out soft-deleted devices and soft-deleted access grants.
func (q *Queries) ListDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]ListDevicesForUserRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesForUserRow
	for rows.Next() {
		var i ListDevicesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UuidFirmware,
			&i.Name,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AccessRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Marks the device as deleted. CASCADE-safe: locations and api_keys
// are not touched (RESTRICT FKs).
func (q *Queries) SoftDeleteDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, id)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET last_seen_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Called by the device auth middleware on every successful request
// from the IoT device. Cheap, no RETURNING.
func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, id)
	return err
}

const updateDeviceName = `-- name: UpdateDeviceName :one
UPDATE devices
SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, uuid_firmware, name, created_at, last_seen_at, deleted_at
`

type UpdateDeviceNameParams struct {
	ID   pgtype.UUID
	Name string
}

// Updates the display name. Returns the updated row, or sql.ErrNoRows
// if the device does not exist or is soft-deleted.
func (q *Queries) UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceName, arg.ID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
	)
	return i, err
}
