// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestLocationForDevice = `-- name: GetLatestLocationForDevice :one
SELECT device_id, recorded_at, latitude, longitude,
       altitude, speed, accuracy, satellites
FROM locations
WHERE device_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

// Returns the most recent location for a device. Used by the live map view.
// Hits the most recent partition first via partition pruning.
func (q *Queries) GetLatestLocationForDevice(ctx context.Context, deviceID pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLatestLocationForDevice, deviceID)
	var i Location
	err := row.Scan(
		&i.DeviceID,
		&i.RecordedAt,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.Accuracy,
		&i.Satellites,
	)
	return i, err
}

const getLocationsForDevice = `-- name: GetLocationsForDevice :many
SELECT device_id, recorded_at, latitude, longitude,
       altitude, speed, accuracy, satellites
FROM locations
WHERE device_id = $1
  AND recorded_at >= $2
  AND recorded_at < $3
ORDER BY recorded_at DESC
`

type GetLocationsForDeviceParams struct {
	DeviceID     pgtype.UUID
	RecordedAt   pgtype.Timestamptz
	RecordedAt_2 pgtype.Timestamptz
}

// Returns the location history for a single device in a time range.
// Partition pruning: the WHERE on recorded_at lets Postgres skip partitions
// that fall outside the [$2, $3) range. Critical for performance as data grows.
// $2 is the inclusive lower bound, $3 is the exclusive upper bound.
func (q *Queries) GetLocationsForDevice(ctx context.Context, arg GetLocationsForDeviceParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocationsForDevice, arg.DeviceID, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.DeviceID,
			&i.RecordedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Speed,
			&i.Accuracy,
			&i.Satellites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationsForUser = `-- name: GetLocationsForUser :many
SELECT
  l.device_id,
  l.recorded_at,
  l.latitude,
  l.longitude,
  l.altitude,
  l.speed,
  l.accuracy,
  l.satellites
FROM locations l
INNER JOIN user_device_access uda
  ON l.device_id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND l.recorded_at >= $2
  AND l.recorded_at < $3
ORDER BY l.recorded_at DESC
`

type GetLocationsForUserParams struct {
	UserID       pgtype.UUID
	RecordedAt   pgtype.Timestamptz
	RecordedAt_2 pgtype.Timestamptz
}

// Returns all locations for all devices a user has access to, in a time range.
// Used for the multi-device dashboard view. Joins through user_device_access
// to filter by the user's authorized devices.
func (q *Queries) GetLocationsForUser(ctx context.Context, arg GetLocationsForUserParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocationsForUser, arg.UserID, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.DeviceID,
			&i.RecordedAt,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Speed,
			&i.Accuracy,
			&i.Satellites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocation = `-- name: InsertLocation :exec
INSERT INTO locations (
  device_id, recorded_at, latitude, longitude,
  altitude, speed, accuracy, satellites
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
ON CONFLICT (device_id, recorded_at) DO NOTHING
`

type InsertLocationParams struct {
	DeviceID   pgtype.UUID
	RecordedAt pgtype.Timestamptz
	Latitude   float64
	Longitude  float64
	Altitude   *float64
	Speed      *float64
	Accuracy   *float64
	Satellites *int32
}

// Idempotent insert for IoT location reports.
// ON CONFLICT (device_id, recorded_at) DO NOTHING handles ESP32 retries
// (same device + same timestamp) without raising an error or duplicating rows.
// This relies on the composite PK (device_id, recorded_at) from migration 000006.
func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) error {
	_, err := q.db.Exec(ctx, insertLocation,
		arg.DeviceID,
		arg.RecordedAt,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.Speed,
		arg.Accuracy,
		arg.Satellites,
	)
	return err
}
