// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Device struct {
	ID           pgtype.UUID
	UuidFirmware string
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type DeviceApiKey struct {
	ID         pgtype.UUID
	DeviceID   pgtype.UUID
	KeyHash    string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Location struct {
	DeviceID   pgtype.UUID
	RecordedAt pgtype.Timestamptz
	Latitude   float64
	Longitude  float64
	Altitude   *float64
	Speed      *float64
	Accuracy   *float64
	Satellites *int32
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
	Lastname  string
}

type UserDeviceAccess struct {
	UserID    pgtype.UUID
	DeviceID  pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
