// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_device_access.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeviceAccess = `-- name: GetDeviceAccess :one
SELECT user_id, device_id, role, created_at, deleted_at
FROM user_device_access
WHERE user_id = $1
  AND device_id = $2
  AND deleted_at IS NULL
`

type GetDeviceAccessParams struct {
	UserID   pgtype.UUID
	DeviceID pgtype.UUID
}

// Returns the access row for a (user, device) pair, or sql.ErrNoRows.
// Used by the API to authorize per-device actions (owner/editor/viewer).
func (q *Queries) GetDeviceAccess(ctx context.Context, arg GetDeviceAccessParams) (UserDeviceAccess, error) {
	row := q.db.QueryRow(ctx, getDeviceAccess, arg.UserID, arg.DeviceID)
	var i UserDeviceAccess
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const grantDeviceAccess = `-- name: GrantDeviceAccess :one
INSERT INTO user_device_access (user_id, device_id, role, created_at, deleted_at)
VALUES ($1, $2, $3, NOW(), NULL)
ON CONFLICT (user_id, device_id) DO UPDATE
  SET role = EXCLUDED.role,
      deleted_at = NULL
RETURNING user_id, device_id, role, created_at, deleted_at
`

type GrantDeviceAccessParams struct {
	UserID   pgtype.UUID
	DeviceID pgtype.UUID
	Role     string
}

// Grants a user access to a device with the given role.
// Idempotent: if access already exists (even soft-deleted), it is reactivated
// with the new role. Used for both first-time grant and role change.
func (q *Queries) GrantDeviceAccess(ctx context.Context, arg GrantDeviceAccessParams) (UserDeviceAccess, error) {
	row := q.db.QueryRow(ctx, grantDeviceAccess, arg.UserID, arg.DeviceID, arg.Role)
	var i UserDeviceAccess
	err := row.Scan(
		&i.UserID,
		&i.DeviceID,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsersForDevice = `-- name: ListUsersForDevice :many
SELECT
  u.id,
  u.email,
  uda.role AS access_role,
  uda.created_at AS access_granted_at
FROM users u
INNER JOIN user_device_access uda
  ON u.id = uda.user_id AND uda.deleted_at IS NULL
WHERE uda.device_id = $1
  AND u.deleted_at IS NULL
ORDER BY uda.created_at DESC
`

type ListUsersForDeviceRow struct {
	ID              pgtype.UUID
	Email           string
	AccessRole      string
	AccessGrantedAt pgtype.Timestamptz
}

// Inverse of ListDevicesForUser: returns all users that have access
// to a given device, with their role. Used in the device admin panel.
func (q *Queries) ListUsersForDevice(ctx context.Context, deviceID pgtype.UUID) ([]ListUsersForDeviceRow, error) {
	rows, err := q.db.Query(ctx, listUsersForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForDeviceRow
	for rows.Next() {
		var i ListUsersForDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AccessRole,
			&i.AccessGrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeviceAccess = `-- name: RevokeDeviceAccess :exec
UPDATE user_device_access
SET deleted_at = NOW()
WHERE user_id = $1
  AND device_id = $2
  AND deleted_at IS NULL
`

type RevokeDeviceAccessParams struct {
	UserID   pgtype.UUID
	DeviceID pgtype.UUID
}

// Soft-deletes the access grant. The pivot row stays in the table for
// audit; queries filter on deleted_at IS NULL.
func (q *Queries) RevokeDeviceAccess(ctx context.Context, arg RevokeDeviceAccessParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceAccess, arg.UserID, arg.DeviceID)
	return err
}
