// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE deleted_at IS NULL
`

// Used by the lazy creation middleware to determine if the incoming
// user is the first one (becomes super_admin) or a regular one.
// Counts only active (non-soft-deleted) users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, lastname, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, lastname, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email    string
	Name     string
	Lastname string
	Role     UserRole
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Lastname  string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Creates a new user with name, lastname, and role.
// Returns the created user.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Lastname,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Lastname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, lastname, role, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Lastname  string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Lookup by email. Used by the lazy user creation flow as a fallback
// when the JWT id is not available.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Lastname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, lastname, role, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Lastname  string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Used by the Authula middleware to load the current user from the DB
// after JWT validation. Filters out soft-deleted users.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Lastname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
SELECT id, email, name, lastname, role, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL AND id != $1
`

type GetUserListRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Lastname  string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Returns all active users except the given user ID.
// Used by admin-level endpoints to list registered users.
func (q *Queries) GetUserList(ctx context.Context, id pgtype.UUID) ([]GetUserListRow, error) {
	rows, err := q.db.Query(ctx, getUserList, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListRow
	for rows.Next() {
		var i GetUserListRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Lastname,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, lastname = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, name, lastname, role, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID
	Name     string
	Lastname string
}

type UpdateUserRow struct {
	ID        pgtype.UUID
	Email     string
	Name      string
	Lastname  string
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// Updates a user's name and lastname. Only the user themselves can update
// their own profile. Returns the updated user.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Lastname)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Lastname,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
