// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS count
FROM users
WHERE deleted_at IS NULL
`

// Used by the lazy creation middleware to determine if the incoming
// user is the first one (becomes super_admin) or a regular one.
// Counts only active (non-soft-deleted) users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, role)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
RETURNING id, email, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID    pgtype.UUID
	Email string
	Role  UserRole
}

// Idempotent user creation. Called by the lazy creation middleware.
// If the user already exists (race condition between two simultaneous
// requests with the same JWT), the insert is a no-op and the function
// returns sql.ErrNoRows. The middleware then falls back to GetUserByID.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

// Lookup by email. Used by the lazy user creation flow as a fallback
// when the JWT id is not available.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// Used by the Authula middleware to load the current user from the DB
// after JWT validation. Filters out soft-deleted users.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserList = `-- name: GetUserList :many
SELECT id, email, role, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL AND id != $1
`

// Returns all active users except the given user ID.
// Used by admin-level endpoints to list registered users.
func (q *Queries) GetUserList(ctx context.Context, id pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserList, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
