name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Run gofmt
        working-directory: backend
        run: |
          echo "::group::Checking formatting"
          test -z "$(gofmt -l .)"
          echo "::endgroup::"

      - name: Run go vet
        working-directory: backend
        run: |
          echo "::group::Running go vet"
          go vet ./...
          echo "::endgroup::"

  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Run tests
        working-directory: backend
        run: |
          echo "::group::Testing backend"
          go test ./internal/app/* -v
          echo "::endgroup::"

  backend-build:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Build project
        working-directory: backend
        run: |
          echo "::group::Build backend"
          go build ./cmd/api
          echo "::endgroup::
